import {
  Form,
  Step,
  Question,
  Theme,
  QuestionType,
  ProgressConfig,
  SubmissionConfig,
  PluginSettings,
  ButtonConfig,
  QuestionValidation,
  Condition,
  ConditionalNavigation,
} from '../types';

// Generate unique IDs
export const generateId = (): string => {
  // Simple ID generator that doesn't require uuid package
  return 'id_' + Math.random().toString(36).substr(2, 9) + '_' + Date.now().toString(36);
};

// Default Theme
export const defaultTheme: Theme = {
  id: generateId(),
  name: 'Professional Theme',
  colors: {
    primary: '#048080',
    secondary: '#023a51',
    accent: '#059999',
    success: '#10B981',
    warning: '#F59E0B',
    error: '#EF4444',
    background: '#FFFFFF',
    surface: '#F9F9F9',
    text: '#023a51',
    textMuted: '#505050',
    border: '#E1E1DF',
  },
  typography: {
    fontFamily: '"Manrope", "Montserrat", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    headingFontFamily: '"Manrope", "Montserrat", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    baseFontSize: 16,
    headingScale: 1.5,
    lineHeight: 1.6,
  },
  spacing: {
    unit: 8,
    formPadding: 32,
    questionGap: 20,
    sectionGap: 32,
  },
  borders: {
    radius: 16,
    width: 1,
    style: 'solid',
  },
  buttons: {
    borderRadius: 100,
    paddingX: 32,
    paddingY: 14,
    fontSize: 16,
    fontWeight: 600,
    textTransform: 'none',
  },
  inputs: {
    borderRadius: 16,
    paddingX: 16,
    paddingY: 14,
    fontSize: 16,
    focusRingWidth: 2,
    focusRingColor: '#048080',
  },
  progressBar: {
    height: 6,
    borderRadius: 3,
    backgroundColor: '#EBEEF3',
    fillColor: '#048080',
    animationType: 'ease-in-out',
  },
};

// Create a fresh copy of the default theme
export const createDefaultTheme = (): Theme => ({
  ...defaultTheme,
  id: generateId(),
  colors: { ...defaultTheme.colors },
  typography: { ...defaultTheme.typography },
  spacing: { ...defaultTheme.spacing },
  borders: { ...defaultTheme.borders },
  buttons: { ...defaultTheme.buttons },
  inputs: { ...defaultTheme.inputs },
  progressBar: { ...defaultTheme.progressBar },
});

// Default Progress Config
export const defaultProgressConfig: ProgressConfig = {
  enabled: true,
  mode: 'exponential',
  position: 'card-top',
  showPercentage: false,
  showStepIndicator: true,
  showStepLabels: false,
  animationDuration: 300,
};

// Default Submission Config
export const defaultSubmissionConfig: SubmissionConfig = {
  method: 'POST',
  url: '',
  headers: {
    'Content-Type': 'application/json',
  },
  includeFields: 'all',
  successMessage: 'Thank you! Your submission has been received.',
  errorMessage: 'Something went wrong. Please try again.',
};

// Default Plugin Settings
export const defaultPluginSettings: PluginSettings = {
  pluginName: 'Custom Form Plugin',
  pluginSlug: 'custom-form-plugin',
  pluginVersion: '1.0.0',
  pluginAuthor: 'Form Builder',
  pluginDescription: 'A custom form plugin generated by WP Form Builder',
  shortcode: 'custom_form',
  menuLocation: 'settings',
};

// Default Button Config
export const defaultBackButton: ButtonConfig = {
  enabled: true,
  label: 'Back',
};

export const defaultContinueButton: ButtonConfig = {
  enabled: true,
  label: 'Continue',
};

export const defaultSubmitButton: ButtonConfig = {
  enabled: true,
  label: 'Submit',
};

// Default Question Validation
export const defaultValidation: QuestionValidation = {
  required: false,
};

// Create a new question
export const createQuestion = (type: QuestionType, gridRow: number = 1): Question => {
  const baseQuestion: Question = {
    id: generateId(),
    type,
    label: getDefaultLabel(type),
    placeholder: getDefaultPlaceholder(type),
    validation: { ...defaultValidation },
    gridColumn: 1,
    gridColumnSpan: 12,
    gridRow,
  };

  // Add options for choice-based questions
  if (['radio', 'checkbox', 'select', 'multiselect'].includes(type)) {
    baseQuestion.options = [
      { id: generateId(), label: 'Option 1', value: 'option1' },
      { id: generateId(), label: 'Option 2', value: 'option2' },
      { id: generateId(), label: 'Option 3', value: 'option3' },
    ];
  }

  return baseQuestion;
};

// Create a new step
export const createStep = (index: number): Step => ({
  id: generateId(),
  title: `Step ${index + 1}`,
  description: '',
  questions: [],
  gridColumns: 12,
  gridGap: 16,
  backButton: { ...defaultBackButton, enabled: index > 0 },
  continueButton: { ...defaultContinueButton },
  conditionalNavigation: [],
  validateOnContinue: true,
});

// Create a new form
export const createForm = (): Form => {
  const firstStep = createStep(0);
  firstStep.backButton.enabled = false;
  
  return {
    id: generateId(),
    name: 'New Form',
    description: '',
    version: '1.0.0',
    steps: [firstStep],
    theme: { ...defaultTheme, id: generateId() },
    progressConfig: { ...defaultProgressConfig },
    submissionConfig: { ...defaultSubmissionConfig },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    pluginSettings: { ...defaultPluginSettings },
  };
};

// Helper functions
function getDefaultLabel(type: QuestionType): string {
  const labels: Record<QuestionType, string> = {
    text: 'Text Field',
    textarea: 'Text Area',
    email: 'Email Address',
    phone: 'Phone Number',
    number: 'Number',
    eircode: 'Eircode',
    numberplate: 'Number Plate',
    radio: 'Single Choice',
    checkbox: 'Multiple Choice',
    select: 'Dropdown',
    multiselect: 'Multi-Select',
    date: 'Date',
    time: 'Time',
    datetime: 'Date & Time',
    file: 'File Upload',
    rating: 'Rating',
    slider: 'Slider',
    hidden: 'Hidden Field',
  };
  return labels[type] || 'Field';
}

function getDefaultPlaceholder(type: QuestionType): string {
  const placeholders: Record<QuestionType, string> = {
    text: 'Enter text...',
    textarea: 'Enter your response...',
    email: 'email@example.com',
    phone: '+1 (555) 000-0000',
    number: '0',
    eircode: 'e.g. D02 X285',
    numberplate: 'e.g. 191-D-12345',
    radio: '',
    checkbox: '',
    select: 'Select an option...',
    multiselect: 'Select options...',
    date: 'Select a date...',
    time: 'Select a time...',
    datetime: 'Select date and time...',
    file: 'Choose a file...',
    rating: '',
    slider: '',
    hidden: '',
  };
  return placeholders[type] || '';
}

// Create a condition
export const createCondition = (): Condition => ({
  id: generateId(),
  logic: 'AND',
  rules: [],
});

// Create conditional navigation
export const createConditionalNavigation = (): ConditionalNavigation => ({
  id: generateId(),
  condition: createCondition(),
  target: { type: 'next' },
  priority: 0,
});

// Question type metadata
export const questionTypeInfo: Record<QuestionType, { label: string; icon: string; category: string }> = {
  text: { label: 'Short Text', icon: 'Aa', category: 'Text' },
  textarea: { label: 'Long Text', icon: '≡', category: 'Text' },
  email: { label: 'Email', icon: '@', category: 'Text' },
  phone: { label: 'Phone', icon: '#', category: 'Text' },
  number: { label: 'Number', icon: '123', category: 'Text' },
  eircode: { label: 'Eircode', icon: 'F92', category: 'Text' },
  numberplate: { label: 'Number Plate', icon: 'DL', category: 'Text' },
  radio: { label: 'Radio Buttons', icon: '○', category: 'Choice' },
  checkbox: { label: 'Checkboxes', icon: '☐', category: 'Choice' },
  select: { label: 'Dropdown', icon: '▾', category: 'Choice' },
  multiselect: { label: 'Multi-Select', icon: '▾▾', category: 'Choice' },
  date: { label: 'Date', icon: 'D', category: 'DateTime' },
  time: { label: 'Time', icon: 'T', category: 'DateTime' },
  datetime: { label: 'Date & Time', icon: 'DT', category: 'DateTime' },
  file: { label: 'File Upload', icon: '⬆', category: 'Advanced' },
  rating: { label: 'Rating', icon: '★', category: 'Advanced' },
  slider: { label: 'Slider', icon: '—○—', category: 'Advanced' },
  hidden: { label: 'Hidden', icon: '∅', category: 'Advanced' },
};

// Group question types by category
export const questionTypesByCategory = Object.entries(questionTypeInfo).reduce(
  (acc, [type, info]) => {
    if (!acc[info.category]) {
      acc[info.category] = [];
    }
    acc[info.category].push({ type: type as QuestionType, ...info });
    return acc;
  },
  {} as Record<string, Array<{ type: QuestionType; label: string; icon: string; category: string }>>
);
