import {
  Form,
  Step,
  Question,
  Theme,
  QuestionType,
  ProgressConfig,
  SubmissionConfig,
  PluginSettings,
  ButtonConfig,
  QuestionValidation,
  Condition,
  ConditionalNavigation,
  PostSubmissionRedirectRule,
  Project,
  ProjectDefaults,
  ProjectPluginSettings,
  LayoutDefaults,
  FormInheritance,
  AnalyticsConfig,
  CURRENT_SCHEMA_VERSION,
} from '../types';

// Generate unique IDs
export const generateId = (): string => {
  // Simple ID generator that doesn't require uuid package
  return 'id_' + Math.random().toString(36).substr(2, 9) + '_' + Date.now().toString(36);
};

// Default Theme
export const defaultTheme: Theme = {
  id: generateId(),
  name: 'Professional Theme',
  colors: {
    primary: '#048080',
    secondary: '#023a51',
    accent: '#059999',
    success: '#10B981',
    warning: '#F59E0B',
    error: '#EF4444',
    background: '#FFFFFF',
    surface: '#F9F9F9',
    text: '#023a51',
    textMuted: '#505050',
    border: '#E1E1DF',
  },
  typography: {
    fontFamily: '"Manrope", "Montserrat", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    headingFontFamily: '"Manrope", "Montserrat", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    baseFontSize: 16,
    headingScale: 1.5,
    lineHeight: 1.6,
  },
  spacing: {
    unit: 8,
    formPadding: 32,
    questionGap: 20,
    sectionGap: 32,
  },
  borders: {
    radius: 16,
    width: 1,
    style: 'solid',
  },
  buttons: {
    borderRadius: 100,
    paddingX: 32,
    paddingY: 14,
    fontSize: 16,
    fontWeight: 600,
    textTransform: 'none',
  },
  inputs: {
    borderRadius: 16,
    paddingX: 16,
    paddingY: 14,
    fontSize: 16,
    focusRingWidth: 2,
    focusRingColor: '#048080',
  },
  progressBar: {
    height: 6,
    borderRadius: 3,
    backgroundColor: '#EBEEF3',
    fillColor: '#048080',
    animationType: 'ease-in-out',
  },
};

// Create a fresh copy of the default theme
export const createDefaultTheme = (): Theme => ({
  ...defaultTheme,
  id: generateId(),
  colors: { ...defaultTheme.colors },
  typography: { ...defaultTheme.typography },
  spacing: { ...defaultTheme.spacing },
  borders: { ...defaultTheme.borders },
  buttons: { ...defaultTheme.buttons },
  inputs: { ...defaultTheme.inputs },
  progressBar: { ...defaultTheme.progressBar },
});

// Default Progress Config
export const defaultProgressConfig: ProgressConfig = {
  enabled: true,
  mode: 'exponential',
  position: 'card-top',
  showPercentage: false,
  showStepIndicator: true,
  showStepLabels: false,
  animationDuration: 300,
};

// Default Submission Config
export const defaultSubmissionConfig: SubmissionConfig = {
  method: 'POST',
  url: '',
  appendWPCidParamsToSubmissionUrl: true,
  headers: {
    'Content-Type': 'application/json',
  },
  includeFields: 'all',
  successMessage: 'Thank you! Your submission has been received.',
  errorMessage: 'Something went wrong. Please try again.',
  skipThankYouPage: false,
  customFields: [],
  successIcon: '✅',
  successBackgroundColor: '',
  successTextColor: '',
  dataLayerEventName: '',
};

// Default Plugin Settings
export const defaultPluginSettings: PluginSettings = {
  pluginName: 'Custom Form Plugin',
  pluginSlug: 'custom-form-plugin',
  pluginVersion: '1.0.0',
  pluginAuthor: 'Form Builder',
  pluginDescription: 'A custom form plugin generated by WP Form Builder',
  shortcode: 'custom_form',
  menuLocation: 'settings',
};

// Default step layout values, shared by new steps and project inheritance.
export const defaultLayoutDefaults: LayoutDefaults = {
  gridColumns: 12,
  gridGap: 16,
  contentAlignment: 'left',
};

// Default Button Config
export const defaultBackButton: ButtonConfig = {
  enabled: true,
  label: 'Back',
  style: 'text',
};

export const defaultContinueButton: ButtonConfig = {
  enabled: true,
  label: 'Continue',
  style: 'contained',
};

export const defaultSubmitButton: ButtonConfig = {
  enabled: true,
  label: 'Submit',
};

// Default Question Validation
export const defaultValidation: QuestionValidation = {
  required: false,
};

// Create a new question
export const createQuestion = (type: QuestionType, gridRow: number = 1): Question => {
  const baseQuestion: Question = {
    id: generateId(),
    type,
    label: getDefaultLabel(type),
    placeholder: getDefaultPlaceholder(type),
    validation: { ...defaultValidation },
    gridColumn: 1,
    gridColumnSpan: 12,
    gridRow,
  };

  // Add options for choice-based questions
  if (['radio', 'checkbox', 'select', 'multiselect'].includes(type)) {
    baseQuestion.options = [
      { id: generateId(), label: 'Option 1', value: 'option1' },
      { id: generateId(), label: 'Option 2', value: 'option2' },
      { id: generateId(), label: 'Option 3', value: 'option3' },
    ];
  }

  // Set defaults for helper text
  if (type === 'helper_text') {
    baseQuestion.helperContent = 'Enter your helper text here...';
    baseQuestion.textAlignment = 'left';
    baseQuestion.hideLabel = true;
    baseQuestion.validation = { required: false };
  }

  // Set defaults for year
  if (type === 'year') {
    baseQuestion.yearInputStyle = 'dropdown';
    baseQuestion.minYear = 1900;
    baseQuestion.maxYear = new Date().getFullYear();
  }

  return baseQuestion;
};

// Create a new step. Optionally seed layout values from project defaults.
export const createStep = (index: number, layout?: LayoutDefaults): Step => {
  const l = layout || defaultLayoutDefaults;
  const step: Step = {
    id: generateId(),
    title: `Step ${index + 1}`,
    description: '',
    questions: [],
    gridColumns: l.gridColumns,
    gridGap: l.gridGap,
    contentAlignment: l.contentAlignment,
    backButton: { ...defaultBackButton, enabled: index > 0 },
    continueButton: { ...defaultContinueButton },
    conditionalNavigation: [],
    validateOnContinue: true,
    autoAdvanceExcludeValues: [],
  };
  if (l.minHeight !== undefined) {
    step.minHeight = l.minHeight;
  }
  return step;
};

export interface CreateFormOptions {
  project?: Project;
}

// Create a new form. When a project is provided, the form is linked to the
// project, inherits every section by default, and seeds its own copies of the
// project defaults so the form remains self-contained for export.
export const createForm = (options: CreateFormOptions = {}): Form => {
  const { project } = options;
  const layout = project?.defaults.layout || defaultLayoutDefaults;
  const firstStep = createStep(0, layout);
  firstStep.backButton.enabled = false;

  const base: Form = {
    id: generateId(),
    name: 'New Form',
    description: '',
    version: '1.0.0',
    steps: [firstStep],
    theme: project ? cloneTheme(project.defaults.theme) : { ...defaultTheme, id: generateId() },
    progressConfig: project ? { ...project.defaults.progress } : { ...defaultProgressConfig },
    submissionConfig: project ? cloneSubmissionConfig(project.defaults.submission) : { ...defaultSubmissionConfig },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    pluginSettings: project ? projectPluginToFormPlugin(project.defaults.plugin) : { ...defaultPluginSettings },
    analyticsConfig: project ? { ...project.defaults.analytics } : { ...defaultAnalyticsConfig },
    schemaVersion: CURRENT_SCHEMA_VERSION,
  };

  if (project) {
    base.projectId = project.id;
    base.childId = generateChildId(base.name);
    base.inheritance = createDefaultInheritance(true);
  } else {
    base.inheritance = createDefaultInheritance(false);
  }

  return base;
};

// ==================== Project & Inheritance helpers ====================

// Deep-ish clone of a theme with a fresh id.
export const cloneTheme = (theme: Theme): Theme => ({
  ...theme,
  id: generateId(),
  colors: { ...theme.colors },
  typography: { ...theme.typography },
  spacing: { ...theme.spacing },
  borders: { ...theme.borders },
  buttons: { ...theme.buttons },
  inputs: { ...theme.inputs },
  progressBar: { ...theme.progressBar },
});

// Clone a submission config (shallow arrays/objects copied).
export const cloneSubmissionConfig = (config: SubmissionConfig): SubmissionConfig => ({
  ...config,
  headers: { ...config.headers },
  includeFields: Array.isArray(config.includeFields) ? [...config.includeFields] : config.includeFields,
  customFields: config.customFields ? config.customFields.map((f) => ({ ...f })) : [],
  postSubmissionRules: config.postSubmissionRules
    ? config.postSubmissionRules.map((r) => ({ ...r }))
    : undefined,
});

// Convert project-level plugin settings into a form-level PluginSettings copy.
export const projectPluginToFormPlugin = (plugin: ProjectPluginSettings): PluginSettings => ({
  pluginName: plugin.pluginName,
  pluginSlug: plugin.pluginSlug,
  pluginVersion: plugin.pluginVersion,
  pluginAuthor: plugin.pluginAuthor,
  pluginDescription: plugin.pluginDescription,
  shortcode: plugin.shortcode,
  menuLocation: plugin.menuLocation,
  menuIcon: plugin.menuIcon,
  sentryDsn: plugin.sentryDsn,
  showSkeleton: plugin.showSkeleton,
});

// Build an inheritance flag set. When `inherit` is true every section is
// inherited from the project; otherwise all sections use form-level values.
export const createDefaultInheritance = (inherit: boolean): FormInheritance => ({
  theme: inherit,
  layout: inherit,
  progress: inherit,
  submission: inherit,
  plugin: inherit,
  analytics: inherit,
});

// Default analytics configuration: tracking disabled until explicitly enabled.
export const defaultAnalyticsConfig: AnalyticsConfig = {
  enabled: false,
  sampleRate: 1,
};

// Generate a stable, URL/shortcode-safe child id from a form name.
export const generateChildId = (name: string): string => {
  const slug = (name || 'form')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/(^_|_$)/g, '');
  return slug || 'form_' + generateId();
};

// Default project-level plugin settings.
export const createProjectPluginSettings = (name: string = 'New Project'): ProjectPluginSettings => {
  const slug = (name || 'project')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '') || 'form-project';
  return {
    pluginName: name,
    pluginSlug: slug,
    pluginVersion: '1.0.0',
    pluginAuthor: 'Form Builder',
    pluginDescription: `Forms for ${name}`,
    shortcode: slug.replace(/-/g, '_') || 'form_project',
    menuLocation: 'settings',
    showSkeleton: true,
  };
};

// Default project defaults bundle.
export const createProjectDefaults = (name: string = 'New Project'): ProjectDefaults => ({
  theme: createDefaultTheme(),
  layout: { ...defaultLayoutDefaults },
  progress: { ...defaultProgressConfig },
  submission: { ...defaultSubmissionConfig },
  plugin: createProjectPluginSettings(name),
  analytics: { ...defaultAnalyticsConfig },
});

// Create a new empty project.
export const createProject = (name: string = 'New Project'): Project => ({
  id: generateId(),
  name,
  description: '',
  schemaVersion: CURRENT_SCHEMA_VERSION,
  defaults: createProjectDefaults(name),
  formIds: [],
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
});

// Upgrade a possibly-legacy form to the current schema. Legacy forms have no
// project linkage or inheritance flags; they become standalone forms whose
// sections all use their own (existing) values, preserving current visuals.
export const migrateForm = (form: Form): Form => {
  const migrated: Form = { ...form };
  if (migrated.schemaVersion === undefined || migrated.schemaVersion < CURRENT_SCHEMA_VERSION) {
    if (!migrated.inheritance) {
      // A form linked to a project defaults to inheriting; a standalone legacy
      // form keeps its own values (no inheritance) to avoid visual drift.
      migrated.inheritance = createDefaultInheritance(false);
    } else if ((migrated.inheritance as any).analytics === undefined) {
      // Schema v3 added the analytics section; default it to not inherited so
      // existing forms are unaffected until the user opts in.
      migrated.inheritance = { ...migrated.inheritance, analytics: false };
    }
    if (migrated.analyticsConfig === undefined) {
      migrated.analyticsConfig = { ...defaultAnalyticsConfig };
    }
    if (migrated.projectId && !migrated.childId) {
      migrated.childId = generateChildId(migrated.name);
    }
    migrated.schemaVersion = CURRENT_SCHEMA_VERSION;
  }
  return migrated;
};

// Resolve the "effective" form used for preview, export and runtime by
// merging project defaults into inherited sections. The result is a new form
// object; the original form (which stores overrides) is not mutated.
export const resolveEffectiveForm = (form: Form, project?: Project | null): Form => {
  if (!project || !form.inheritance) {
    return form;
  }
  const inh = form.inheritance;
  const d = project.defaults;
  const effective: Form = { ...form };

  if (inh.theme) {
    effective.theme = cloneTheme(d.theme);
  }
  if (inh.progress) {
    effective.progressConfig = { ...d.progress };
  }
  if (inh.submission) {
    // Preserve form-specific submission destination fields when present,
    // otherwise fall back entirely to project defaults.
    effective.submissionConfig = cloneSubmissionConfig(d.submission);
  }
  if (inh.plugin) {
    effective.pluginSettings = projectPluginToFormPlugin(d.plugin);
  }
  if (inh.analytics) {
    effective.analyticsConfig = { ...d.analytics };
  }
  if (inh.layout) {
    effective.steps = form.steps.map((step) => ({
      ...step,
      gridColumns: d.layout.gridColumns,
      gridGap: d.layout.gridGap,
      contentAlignment: d.layout.contentAlignment,
      minHeight: d.layout.minHeight !== undefined ? d.layout.minHeight : step.minHeight,
    }));
  }

  return effective;
};

// Helper functions
function getDefaultLabel(type: QuestionType): string {
  const labels: Record<QuestionType, string> = {
    text: 'Text Field',
    textarea: 'Text Area',
    email: 'Email Address',
    phone: 'Phone Number',
    number: 'Number',
    currency: 'Currency',
    eircode: 'Eircode',
    numberplate: 'Number Plate',
    privacy_policy: 'I agree to the Privacy Policy',
    radio: 'Single Choice',
    checkbox: 'Multiple Choice',
    select: 'Dropdown',
    multiselect: 'Multi-Select',
    date: 'Date',
    time: 'Time',
    datetime: 'Date & Time',
    year: 'Year',
    file: 'File Upload',
    rating: 'Rating',
    slider: 'Slider',
    hidden: 'Hidden Field',
    helper_text: 'Helper Text',
  };
  return labels[type] || 'Field';
}

function getDefaultPlaceholder(type: QuestionType): string {
  const placeholders: Record<QuestionType, string> = {
    text: 'Enter text...',
    textarea: 'Enter your response...',
    email: 'email@example.com',
    phone: '+1 (555) 000-0000',
    number: '0',
    currency: '0.00',
    eircode: 'e.g. D02 X285',
    numberplate: 'e.g. 191-D-12345',
    privacy_policy: '',
    radio: '',
    checkbox: '',
    select: 'Select an option...',
    multiselect: 'Select options...',
    date: 'Select a date...',
    time: 'Select a time...',
    datetime: 'Select date and time...',
    year: 'e.g. 2021',
    file: 'Choose a file...',
    rating: '',
    slider: '',
    hidden: '',
    helper_text: '',
  };
  return placeholders[type] || '';
}

// Create a condition
export const createCondition = (): Condition => ({
  id: generateId(),
  logic: 'AND',
  rules: [],
});

// Create conditional navigation
export const createConditionalNavigation = (): ConditionalNavigation => ({
  id: generateId(),
  condition: createCondition(),
  target: { type: 'next' },
  priority: 0,
});

// Create post-submission redirect rule
export const createPostSubmissionRule = (): PostSubmissionRedirectRule => ({
  id: generateId(),
  priority: 0,
  condition: createCondition(),
  target: { type: 'url', url: '' },
});

// Question type metadata
export const questionTypeInfo: Record<QuestionType, { label: string; icon: string; category: string }> = {
  text: { label: 'Short Text', icon: 'Aa', category: 'Text' },
  textarea: { label: 'Long Text', icon: '≡', category: 'Text' },
  email: { label: 'Email', icon: '@', category: 'Text' },
  phone: { label: 'Phone', icon: '#', category: 'Text' },
  number: { label: 'Number', icon: '123', category: 'Text' },
  currency: { label: 'Currency', icon: '€', category: 'Text' },
  eircode: { label: 'Eircode', icon: 'F92', category: 'Text' },
  numberplate: { label: 'Number Plate', icon: 'DL', category: 'Text' },
  privacy_policy: { label: 'Privacy Policy', icon: '🛡️', category: 'Advanced' },
  radio: { label: 'Radio Buttons', icon: '○', category: 'Choice' },
  checkbox: { label: 'Checkboxes', icon: '☐', category: 'Choice' },
  select: { label: 'Dropdown', icon: '▾', category: 'Choice' },
  multiselect: { label: 'Multi-Select', icon: '▾▾', category: 'Choice' },
  date: { label: 'Date', icon: 'D', category: 'DateTime' },
  time: { label: 'Time', icon: 'T', category: 'DateTime' },
  datetime: { label: 'Date & Time', icon: 'DT', category: 'DateTime' },
  year: { label: 'Year', icon: 'YYYY', category: 'DateTime' },
  file: { label: 'File Upload', icon: '⬆', category: 'Advanced' },
  rating: { label: 'Rating', icon: '★', category: 'Advanced' },
  slider: { label: 'Slider', icon: '—○—', category: 'Advanced' },
  hidden: { label: 'Hidden', icon: '∅', category: 'Advanced' },
  helper_text: { label: 'Helper Text', icon: '¶', category: 'Layout' },
};

// Group question types by category
export const questionTypesByCategory = Object.entries(questionTypeInfo).reduce(
  (acc, [type, info]) => {
    if (!acc[info.category]) {
      acc[info.category] = [];
    }
    acc[info.category].push({ type: type as QuestionType, ...info });
    return acc;
  },
  {} as Record<string, Array<{ type: QuestionType; label: string; icon: string; category: string }>>
);
