import { Form, Theme, Question, Step } from '../types';

// Helper to escape single quotes for PHP strings
function escapePhpString(str: string): string {
  if (!str) return '';
  // Escape backslashes first, then single quotes
  return str.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

// Generate Theme CSS
export function generateThemeCSS(theme: Theme): string {
  return `/**
 * Form Styles
 * Generated by WP Form Builder
 * Uses CSS specificity to prevent WordPress theme conflicts
 */

/* CSS Reset for form container to prevent theme conflicts */
.wp-form,
.wp-form *,
.wp-form *::before,
.wp-form *::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

.wp-form {
  /* CSS Custom Properties scoped to form */
  --wp-form-primary: ${theme.colors.primary};
  --wp-form-secondary: ${theme.colors.secondary};
  --wp-form-accent: ${theme.colors.accent};
  --wp-form-success: ${theme.colors.success};
  --wp-form-warning: ${theme.colors.warning};
  --wp-form-error: ${theme.colors.error};
  --wp-form-background: ${theme.colors.background};
  --wp-form-surface: ${theme.colors.surface};
  --wp-form-text: ${theme.colors.text};
  --wp-form-text-muted: ${theme.colors.textMuted};
  --wp-form-border: ${theme.colors.border};
  
  /* Typography */
  --wp-form-font-family: ${theme.typography.fontFamily};
  --wp-form-heading-font: ${theme.typography.headingFontFamily};
  --wp-form-font-size: ${theme.typography.baseFontSize}px;
  --wp-form-line-height: ${theme.typography.lineHeight};
  
  /* Spacing */
  --wp-form-spacing-unit: ${theme.spacing.unit}px;
  --wp-form-padding: ${theme.spacing.formPadding}px;
  --wp-form-question-gap: ${theme.spacing.questionGap}px;
  --wp-form-section-gap: ${theme.spacing.sectionGap}px;
  
  /* Borders */
  --wp-form-border-radius: ${theme.borders.radius}px;
  --wp-form-border-width: ${theme.borders.width}px;
  --wp-form-border-style: ${theme.borders.style};
  
  /* Progress Bar */
  --wp-form-progress-height: ${theme.progressBar.height}px;
  --wp-form-progress-radius: ${theme.progressBar.borderRadius}px;
  --wp-form-progress-bg: ${theme.progressBar.backgroundColor};
  --wp-form-progress-fill: ${theme.progressBar.fillColor};
  
  /* Apply base styles */
  font-family: var(--wp-form-font-family) !important;
  font-size: var(--wp-form-font-size) !important;
  line-height: var(--wp-form-line-height) !important;
  color: var(--wp-form-text) !important;
  width: 100%;
  box-sizing: border-box;
}

/* Default card styling - applies when no progress position variant */
.wp-form:not(.progress-top):not(.progress-bottom):not(.progress-card-top):not(.progress-card-bottom):not(.progress-inline) {
  background-color: var(--wp-form-background);
  border-radius: var(--wp-form-border-radius);
  overflow: hidden;
}

/* Content wrapper - this gets the padding */
.wp-form-content {
  padding: var(--wp-form-padding);
}

/* Progress Bar */
.wp-form-progress {
  margin-bottom: var(--wp-form-section-gap);
}

.wp-form-progress-indicator {
  text-align: center;
  margin-bottom: calc(var(--wp-form-spacing-unit) * 2);
  color: var(--wp-form-text-muted);
  font-size: 0.875em;
}

.wp-form-progress-bar {
  height: var(--wp-form-progress-height);
  background-color: var(--wp-form-progress-bg);
  border-radius: var(--wp-form-progress-radius);
  overflow: hidden;
}

.wp-form-progress-fill {
  height: 100%;
  background-color: var(--wp-form-progress-fill);
  border-radius: var(--wp-form-progress-radius);
  transition: width 0.3s ${theme.progressBar.animationType};
}

.wp-form-progress-percentage {
  text-align: right;
  margin-top: calc(var(--wp-form-spacing-unit) / 2);
  font-size: 0.75em;
  color: var(--wp-form-text-muted);
}

/* Step */
.wp-form-step {
  background-color: transparent;
  padding: 0;
  border-radius: 0;
  border: none;
}

.wp-form-step-title {
  font-family: var(--wp-form-heading-font);
  font-size: calc(var(--wp-form-font-size) * ${theme.typography.headingScale});
  font-weight: 600;
  margin: 0 0 calc(var(--wp-form-spacing-unit) * 2);
  color: var(--wp-form-text);
}

.wp-form-step-description {
  color: var(--wp-form-text-muted);
  margin-bottom: var(--wp-form-section-gap);
}

/* Questions Grid */
.wp-form-questions {
  display: grid;
  gap: var(--wp-form-question-gap);
}

/* Question Field */
.wp-form-field {
  display: flex;
  flex-direction: column;
  gap: calc(var(--wp-form-spacing-unit) / 2);
}

.wp-form-field-label {
  font-weight: 500;
  color: var(--wp-form-text);
}

.wp-form-field-required {
  color: var(--wp-form-error);
  margin-left: 4px;
}

.wp-form-field-input,
.wp-form-field-textarea,
.wp-form-field-select {
  width: 100%;
  padding: ${theme.inputs.paddingY}px ${theme.inputs.paddingX}px;
  font-size: ${theme.inputs.fontSize}px;
  font-family: inherit;
  border: var(--wp-form-border-width) var(--wp-form-border-style) var(--wp-form-border);
  border-radius: ${theme.inputs.borderRadius}px;
  background-color: var(--wp-form-surface);
  color: var(--wp-form-text);
  transition: border-color 0.2s, box-shadow 0.2s;
}

.wp-form-field-input:focus,
.wp-form-field-textarea:focus,
.wp-form-field-select:focus {
  outline: none;
  border-color: var(--wp-form-primary);
  box-shadow: 0 0 0 ${theme.inputs.focusRingWidth}px ${theme.inputs.focusRingColor}40;
}

.wp-form-field-textarea {
  min-height: 100px;
  resize: vertical;
}

.wp-form-field-help {
  font-size: 0.875em;
  color: var(--wp-form-text-muted);
}

.wp-form-field-error {
  font-size: 0.875em;
  color: var(--wp-form-error);
}

.wp-form-field.has-error .wp-form-field-input,
.wp-form-field.has-error .wp-form-field-textarea,
.wp-form-field.has-error .wp-form-field-select {
  border-color: var(--wp-form-error);
}

/* Radio & Checkbox - Modern Card Style */
.wp-form-options {
  display: flex;
  flex-direction: column;
  gap: calc(var(--wp-form-spacing-unit) * 1.5);
}

.wp-form-option {
  display: flex;
  align-items: center;
  gap: calc(var(--wp-form-spacing-unit) * 1.5);
  cursor: pointer;
  padding: calc(var(--wp-form-spacing-unit) * 2);
  background: var(--wp-form-surface);
  border: 2px solid var(--wp-form-border);
  border-radius: calc(var(--wp-form-border-radius) * 0.75);
  transition: all 0.2s ease;
  position: relative;
}

.wp-form-option:hover {
  border-color: var(--wp-form-primary);
  background: var(--wp-form-background);
}

.wp-form-option.selected,
.wp-form-option:has(input:checked) {
  border-color: var(--wp-form-primary);
  background: color-mix(in srgb, var(--wp-form-primary) 5%, var(--wp-form-background));
  box-shadow: 0 0 0 1px var(--wp-form-primary);
}

.wp-form-option input[type="checkbox"],
.wp-form-option input[type="radio"] {
  appearance: none;
  -webkit-appearance: none;
  width: 22px;
  height: 22px;
  border: 2px solid var(--wp-form-border);
  background: var(--wp-form-background);
  cursor: pointer;
  flex-shrink: 0;
  margin: 0;
  position: relative;
  transition: all 0.2s ease;
}

.wp-form-option input[type="radio"] {
  border-radius: 50%;
}

.wp-form-option input[type="checkbox"] {
  border-radius: 4px;
}

.wp-form-option input[type="checkbox"]:checked,
.wp-form-option input[type="radio"]:checked {
  background: var(--wp-form-primary);
  border-color: var(--wp-form-primary);
}

.wp-form-option input[type="checkbox"]:checked::after {
  content: '';
  position: absolute;
  left: 6px;
  top: 2px;
  width: 5px;
  height: 10px;
  border: solid white;
  border-width: 0 2px 2px 0;
  transform: rotate(45deg);
}

.wp-form-option input[type="radio"]:checked::after {
  content: '';
  position: absolute;
  left: 50%;
  top: 50%;
  width: 8px;
  height: 8px;
  background: white;
  border-radius: 50%;
  transform: translate(-50%, -50%);
}

.wp-form-option-label {
  font-weight: 500;
  color: var(--wp-form-text);
  flex: 1;
}

/* Rating */
.wp-form-rating {
  display: flex;
  gap: 4px;
}

.wp-form-rating-star {
  background: none;
  border: none;
  cursor: pointer;
  font-size: 1.5em;
  padding: 0;
  opacity: 0.3;
  transition: opacity 0.2s;
}

.wp-form-rating-star.active,
.wp-form-rating-star:hover {
  opacity: 1;
}

/* Slider */
.wp-form-slider {
  display: flex;
  align-items: center;
  gap: calc(var(--wp-form-spacing-unit) * 2);
}

.wp-form-slider input[type="range"] {
  flex: 1;
  height: 8px;
  -webkit-appearance: none;
  background: var(--wp-form-border);
  border-radius: 4px;
  outline: none;
}

.wp-form-slider input[type="range"]::-webkit-slider-thumb {
  -webkit-appearance: none;
  width: 20px;
  height: 20px;
  background: var(--wp-form-primary);
  border-radius: 50%;
  cursor: pointer;
}

.wp-form-slider-value {
  min-width: 40px;
  text-align: center;
  font-weight: 500;
}

/* Navigation */
.wp-form-navigation {
  display: flex;
  justify-content: space-between;
  margin-top: var(--wp-form-section-gap);
  gap: var(--wp-form-question-gap);
}

.wp-form-btn {
  padding: ${theme.buttons.paddingY}px ${theme.buttons.paddingX}px;
  font-size: ${theme.buttons.fontSize}px;
  font-weight: ${theme.buttons.fontWeight};
  text-transform: ${theme.buttons.textTransform};
  border-radius: ${theme.buttons.borderRadius}px;
  border: none;
  cursor: pointer;
  transition: background-color 0.2s, transform 0.1s;
}

.wp-form-btn:hover {
  transform: translateY(-1px);
}

.wp-form-btn:active {
  transform: translateY(0);
}

.wp-form-btn:disabled {
  opacity: 0.6;
  cursor: not-allowed;
  transform: none;
}

.wp-form-btn-back {
  background-color: var(--wp-form-surface);
  color: var(--wp-form-text);
  border: var(--wp-form-border-width) var(--wp-form-border-style) var(--wp-form-border);
}

.wp-form-btn-back:hover {
  background-color: var(--wp-form-background);
}

.wp-form-btn-continue,
.wp-form-btn-submit {
  background-color: var(--wp-form-primary);
  color: white;
  margin-left: auto;
}

.wp-form-btn-continue:hover,
.wp-form-btn-submit:hover {
  background-color: ${darkenColor(theme.colors.primary, 10)};
}

/* Success State */
.wp-form-success {
  text-align: center;
  padding: var(--wp-form-section-gap);
}

.wp-form-success-icon {
  font-size: 3em;
  margin-bottom: var(--wp-form-spacing-unit);
}

.wp-form-success-message {
  font-size: 1.25em;
  color: var(--wp-form-success);
  margin-bottom: var(--wp-form-section-gap);
}

/* Loading State */
.wp-form-loading {
  position: relative;
  pointer-events: none;
}

.wp-form-loading::after {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(255, 255, 255, 0.7);
  z-index: 10;
}

.wp-form-loading .wp-form-btn-submit,
.wp-form-loading .wp-form-btn-continue {
  position: relative;
  pointer-events: none;
  opacity: 0.8;
}

.wp-form-loading .wp-form-btn-submit::after,
.wp-form-loading .wp-form-btn-continue::after {
  content: '';
  display: inline-block;
  width: 16px;
  height: 16px;
  border: 2px solid transparent;
  border-top-color: currentColor;
  border-radius: 50%;
  animation: wp-form-spin 0.8s linear infinite;
  margin-left: 8px;
  vertical-align: middle;
}

@keyframes wp-form-spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

/* Submission Error */
.wp-form-submission-error {
  background-color: #FEE2E2;
  color: #DC2626;
  padding: var(--wp-form-spacing-unit) calc(var(--wp-form-spacing-unit) * 2);
  border-radius: var(--wp-form-border-radius);
  margin-bottom: var(--wp-form-section-gap);
  border: 1px solid #FECACA;
}

/* Progress Bar Position Variants */

/* Card Top - Progress bar as top border of step card */
.wp-form.progress-card-top {
  background: transparent !important;
  background-color: transparent !important;
  border: none !important;
  border-radius: 0 !important;
  box-shadow: none !important;
}

.wp-form.progress-card-top .wp-form-content {
  background-color: var(--wp-form-background);
  border: var(--wp-form-border-width) var(--wp-form-border-style) var(--wp-form-border);
  border-radius: var(--wp-form-border-radius);
  overflow: hidden;
  padding: 0;
}

.wp-form.progress-card-top .wp-form-progress {
  margin: 0;
  padding: 0;
  width: 100%;
}

.wp-form.progress-card-top .wp-form-progress-bar {
  border-radius: 0;
  height: var(--wp-form-progress-height);
  margin: 0;
}

.wp-form.progress-card-top .wp-form-progress-fill {
  border-radius: 0;
}

/* The form container gets the padding for card-top */
.wp-form.progress-card-top .wp-form-container {
  padding: var(--wp-form-padding);
}

.wp-form.progress-card-top .wp-form-success {
  padding: var(--wp-form-padding);
}

/* Hide step indicator and percentage for card positions */
.wp-form.progress-card-top .wp-form-progress-indicator,
.wp-form.progress-card-top .wp-form-progress-percentage,
.wp-form.progress-card-bottom .wp-form-progress-indicator,
.wp-form.progress-card-bottom .wp-form-progress-percentage {
  display: none;
}

/* Card Bottom - Progress bar as bottom border of step card */
.wp-form.progress-card-bottom {
  background: transparent !important;
  background-color: transparent !important;
  border: none !important;
  border-radius: 0 !important;
  box-shadow: none !important;
}

.wp-form.progress-card-bottom .wp-form-content {
  background-color: var(--wp-form-background);
  border: var(--wp-form-border-width) var(--wp-form-border-style) var(--wp-form-border);
  border-radius: var(--wp-form-border-radius);
  overflow: hidden;
  padding: 0;
}

.wp-form.progress-card-bottom .wp-form-progress {
  margin: 0;
  padding: 0;
  width: 100%;
}

.wp-form.progress-card-bottom .wp-form-progress-bar {
  border-radius: 0;
  height: var(--wp-form-progress-height);
  margin: 0;
}

.wp-form.progress-card-bottom .wp-form-progress-fill {
  border-radius: 0;
}

/* The form container gets the padding for card-bottom */
.wp-form.progress-card-bottom .wp-form-container {
  padding: var(--wp-form-padding);
}

.wp-form.progress-card-bottom .wp-form-success {
  padding: var(--wp-form-padding);
}

/* Top - Above the form card */
.wp-form.progress-top {
  background: transparent !important;
  border: none;
  border-radius: 0;
}

.wp-form.progress-top .wp-form-content {
  background-color: var(--wp-form-background);
  border: var(--wp-form-border-width) var(--wp-form-border-style) var(--wp-form-border);
  border-radius: var(--wp-form-border-radius);
}

.wp-form.progress-top .wp-form-progress {
  margin-bottom: var(--wp-form-section-gap);
}

/* Bottom - Below the form card */
.wp-form.progress-bottom {
  background: transparent !important;
  border: none;
  border-radius: 0;
}

.wp-form.progress-bottom .wp-form-content {
  background-color: var(--wp-form-background);
  border: var(--wp-form-border-width) var(--wp-form-border-style) var(--wp-form-border);
  border-radius: var(--wp-form-border-radius);
}

.wp-form.progress-bottom .wp-form-progress {
  margin-top: var(--wp-form-section-gap);
  margin-bottom: 0;
}

/* Inline - Inside step header */
.wp-form.progress-inline {
  background-color: var(--wp-form-background);
  border-radius: var(--wp-form-border-radius);
  overflow: hidden;
}

.wp-form.progress-inline .wp-form-progress {
  margin-bottom: var(--wp-form-spacing-unit);
}

.wp-form.progress-inline .wp-form-step-title {
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-wrap: wrap;
  gap: var(--wp-form-spacing-unit);
}

.wp-form.progress-inline .wp-form-progress-indicator {
  margin: 0;
  font-size: 0.875em;
}

/* Responsive */
@media (max-width: 768px) {
  .wp-form {
    padding: 0;
  }
  
  .wp-form-content {
    padding: calc(var(--wp-form-padding) * 0.75);
  }
  
  /* Stack questions vertically on mobile */
  .wp-form-questions {
    display: flex !important;
    flex-direction: column;
    gap: var(--wp-form-spacing-unit);
  }
  
  .wp-form-field {
    grid-column: 1 / -1 !important;
    width: 100%;
  }
  
  .wp-form-navigation {
    flex-direction: column;
    gap: calc(var(--wp-form-spacing-unit) / 2);
  }
  
  .wp-form-btn {
    width: 100%;
  }
  
  .wp-form-btn-continue {
    margin-left: 0;
  }
  
  /* Adjust step title */
  .wp-form-step-title {
    font-size: 1.25rem;
  }
  
  /* Progress bar adjustments */
  .wp-form-progress {
    padding: calc(var(--wp-form-padding) * 0.5);
  }
  
  .wp-form-progress-indicator {
    font-size: 0.8rem;
  }
  
  /* Form field adjustments */
  .wp-form-label {
    font-size: 0.9rem;
  }
  
  .wp-form-input,
  .wp-form-select,
  .wp-form-textarea {
    font-size: 16px; /* Prevents zoom on iOS */
    padding: 12px;
  }
  
  /* Rating adjustments */
  .wp-form-rating-label {
    font-size: 1.5rem;
    padding: 0.5rem;
  }
  
  /* Radio/Checkbox adjustments */
  .wp-form-radio-label,
  .wp-form-checkbox-label {
    padding: 12px;
    font-size: 0.9rem;
  }
}

@media (max-width: 480px) {
  .wp-form-content {
    padding: calc(var(--wp-form-padding) * 0.5);
  }
  
  .wp-form-step-title {
    font-size: 1.1rem;
  }
  
  .wp-form-step-description {
    font-size: 0.85rem;
  }
  
  .wp-form-btn {
    padding: 14px 20px;
    font-size: 1rem;
  }
}

/* Eircode Field */
.wp-form-eircode-input {
  text-transform: uppercase;
}

.wp-form-eircode-finder {
  display: block;
  margin-top: 4px;
  font-size: 0.875em;
  color: var(--wp-form-primary);
  text-decoration: none;
}

.wp-form-eircode-finder:hover {
  text-decoration: underline;
}

/* Number Plate Field */
.wp-form-numberplate-input {
  text-transform: uppercase;
}

/* Custom CSS */
${theme.customCSS || ''}
`;
}

// Helper to darken color
function darkenColor(color: string, percent: number): string {
  const num = parseInt(color.replace('#', ''), 16);
  const amt = Math.round(2.55 * percent);
  const R = Math.max((num >> 16) - amt, 0);
  const G = Math.max(((num >> 8) & 0x00FF) - amt, 0);
  const B = Math.max((num & 0x0000FF) - amt, 0);
  return '#' + (0x1000000 + R * 0x10000 + G * 0x100 + B).toString(16).slice(1);
}

// Generate Form HTML Template
export function generateFormHTML(form: Form): string {
  const { pluginSettings, steps, progressConfig } = form;
  const successMsg = escapePhpString(form.submissionConfig.successMessage);
  const position = progressConfig.position || 'top';
  const positionClass = progressConfig.enabled ? `progress-${position}` : '';
  const isCardPosition = position === 'card-top' || position === 'card-bottom';
  
  // For card positions, progress bar goes outside the content wrapper
  const progressBarHTML = `
    <div class="wp-form-progress">
        <?php if (${progressConfig.showStepIndicator ? 'true' : 'false'} && !${isCardPosition ? 'true' : 'false'}): ?>
        <div class="wp-form-progress-indicator">
            <span class="current-step">1</span> of <span class="total-steps">${steps.length}</span>
        </div>
        <?php endif; ?>
        
        <div class="wp-form-progress-bar">
            <div class="wp-form-progress-fill" style="width: 0%;"></div>
        </div>
        
        <?php if (${progressConfig.showPercentage ? 'true' : 'false'} && !${isCardPosition ? 'true' : 'false'}): ?>
        <div class="wp-form-progress-percentage">0%</div>
        <?php endif; ?>
    </div>`;
  
  return `<?php
/**
 * Form Template
 */

if (!defined('ABSPATH')) {
    exit;
}
?>

<div class="wp-form ${positionClass}" id="${pluginSettings.pluginSlug}-form" data-form-id="<?php echo esc_attr('${escapePhpString(form.id)}'); ?>">
    
    <?php if (${progressConfig.enabled ? 'true' : 'false'} && '${position}' === 'top'): ?>
    ${progressBarHTML}
    <?php endif; ?>
    
    <div class="wp-form-content">
        <?php if (${progressConfig.enabled ? 'true' : 'false'} && ('${position}' === 'card-top' || '${position}' === 'inline')): ?>
        ${progressBarHTML}
        <?php endif; ?>
        
        <form class="wp-form-container" method="post">
            <?php wp_nonce_field('${escapePhpString(pluginSettings.pluginSlug)}_nonce', '${escapePhpString(pluginSettings.pluginSlug)}_nonce_field'); ?>
            
            ${steps.map((step, index) => generateStepHTML(step, index, steps.length)).join('\n            ')}
            
        </form>
        
        <div class="wp-form-success" style="display: none;">
            <div class="wp-form-success-icon">✅</div>
            <p class="wp-form-success-message"><?php echo esc_html('${successMsg}'); ?></p>
        </div>
        
        <?php if (${progressConfig.enabled ? 'true' : 'false'} && '${position}' === 'card-bottom'): ?>
        ${progressBarHTML}
        <?php endif; ?>
    </div>
    
    <?php if (${progressConfig.enabled ? 'true' : 'false'} && '${position}' === 'bottom'): ?>
    ${progressBarHTML}
    <?php endif; ?>
    
</div>
`;
}

function generateStepHTML(step: Step, index: number, totalSteps: number): string {
  const isFirst = index === 0;
  const isLast = index === totalSteps - 1;
  const stepTitle = escapePhpString(step.title);
  const stepDesc = escapePhpString(step.description || '');
  const backLabel = escapePhpString(step.backButton.label);
  const continueLabel = escapePhpString(isLast ? 'Submit' : step.continueButton.label);
  
  return `
        <div class="wp-form-step" data-step="${index}" data-step-id="${escapePhpString(step.id)}" ${index > 0 ? 'style="display: none;"' : ''}>
            <h2 class="wp-form-step-title"><?php echo esc_html('${stepTitle}'); ?></h2>
            ${step.description ? `<p class="wp-form-step-description"><?php echo esc_html('${stepDesc}'); ?></p>` : ''}
            
            <div class="wp-form-questions" style="grid-template-columns: repeat(${step.gridColumns}, 1fr); gap: ${step.gridGap}px;">
                ${step.questions.map(q => generateQuestionHTML(q, step.gridColumns)).join('\n                ')}
            </div>
            
            <div class="wp-form-navigation">
                ${step.backButton.enabled && !isFirst ? `
                <button type="button" class="wp-form-btn wp-form-btn-back" data-action="back">
                    <?php echo esc_html('${backLabel}'); ?>
                </button>
                ` : '<div></div>'}
                
                ${step.continueButton.enabled ? `
                <button type="button" class="wp-form-btn ${isLast ? 'wp-form-btn-submit' : 'wp-form-btn-continue'}" data-action="${isLast ? 'submit' : 'continue'}">
                    <?php echo esc_html('${continueLabel}'); ?>
                </button>
                ` : ''}
            </div>
        </div>`;
}

function generateQuestionHTML(question: Question, gridColumns: number): string {
  const gridRow = question.gridRow || 'auto';
  const style = `grid-column: ${question.gridColumn} / span ${question.gridColumnSpan}; grid-row: ${gridRow};`;
  const required = question.validation.required;
  const questionId = escapePhpString(question.id);
  // Use fieldName if set, otherwise fall back to question id
  const fieldName = escapePhpString(question.fieldName || question.id);
  const placeholder = escapePhpString(question.placeholder || '');
  const label = escapePhpString(question.label);
  const helpText = escapePhpString(question.helpText || '');
  const defaultVal = escapePhpString(question.defaultValue || '');
  
  let inputHTML = '';
  
  switch (question.type) {
    case 'text':
    case 'email':
    case 'phone':
      inputHTML = `<input type="${question.type === 'email' ? 'email' : question.type === 'phone' ? 'tel' : 'text'}" 
                    class="wp-form-field-input" 
                    name="${fieldName}" 
                    id="${questionId}"
                    placeholder="<?php echo esc_attr('${placeholder}'); ?>"
                    ${required ? 'required' : ''}>`;
      break;
    
    case 'number':
      inputHTML = `<input type="number" 
                    class="wp-form-field-input" 
                    name="${fieldName}" 
                    id="${questionId}"
                    placeholder="<?php echo esc_attr('${placeholder}'); ?>"
                    ${question.validation.min !== undefined ? `min="${question.validation.min}"` : ''}
                    ${question.validation.max !== undefined ? `max="${question.validation.max}"` : ''}
                    ${required ? 'required' : ''}>`;
      break;
    
    case 'textarea':
      inputHTML = `<textarea 
                    class="wp-form-field-textarea" 
                    name="${fieldName}" 
                    id="${questionId}"
                    placeholder="<?php echo esc_attr('${placeholder}'); ?>"
                    ${required ? 'required' : ''}></textarea>`;
      break;
    
    case 'radio':
      inputHTML = `<div class="wp-form-options">
                    ${question.options?.map(opt => `
                    <label class="wp-form-option">
                        <input type="radio" name="${fieldName}" value="${escapePhpString(opt.value)}" ${required ? 'required' : ''}>
                        <span class="wp-form-option-label"><?php echo esc_html('${escapePhpString(opt.label)}'); ?></span>
                    </label>`).join('') || ''}
                </div>`;
      break;
    
    case 'checkbox':
      inputHTML = `<div class="wp-form-options">
                    ${question.options?.map(opt => `
                    <label class="wp-form-option">
                        <input type="checkbox" name="${fieldName}[]" value="${escapePhpString(opt.value)}">
                        <span class="wp-form-option-label"><?php echo esc_html('${escapePhpString(opt.label)}'); ?></span>
                    </label>`).join('') || ''}
                </div>`;
      break;
    
    case 'select':
      inputHTML = `<select class="wp-form-field-select" name="${fieldName}" id="${questionId}" ${required ? 'required' : ''}>
                    <option value=""><?php echo esc_html('${placeholder || 'Select...'}'); ?></option>
                    ${question.options?.map(opt => `
                    <option value="${escapePhpString(opt.value)}"><?php echo esc_html('${escapePhpString(opt.label)}'); ?></option>`).join('') || ''}
                </select>`;
      break;
    
    case 'date':
      inputHTML = `<input type="date" class="wp-form-field-input" name="${fieldName}" id="${questionId}" ${required ? 'required' : ''}>`;
      break;
    
    case 'time':
      inputHTML = `<input type="time" class="wp-form-field-input" name="${fieldName}" id="${questionId}" ${required ? 'required' : ''}>`;
      break;
    
    case 'rating':
      inputHTML = `<div class="wp-form-rating" data-name="${fieldName}">
                    <?php for ($i = 1; $i <= 5; $i++): ?>
                    <button type="button" class="wp-form-rating-star" data-value="<?php echo $i; ?>">⭐</button>
                    <?php endfor; ?>
                    <input type="hidden" name="${fieldName}" value="">
                </div>`;
      break;
    
    case 'slider':
      inputHTML = `<div class="wp-form-slider">
                    <input type="range" name="${fieldName}" id="${questionId}" 
                           min="${question.validation.min || 0}" 
                           max="${question.validation.max || 100}" 
                           value="${question.defaultValue || 50}">
                    <span class="wp-form-slider-value">${question.defaultValue || 50}</span>
                </div>`;
      break;
    
    case 'file':
      inputHTML = `<input type="file" class="wp-form-field-input" name="${fieldName}" id="${questionId}" ${required ? 'required' : ''}>`;
      break;
    
    case 'eircode':
      inputHTML = `<input type="text" 
                    class="wp-form-field-input wp-form-eircode-input" 
                    name="${fieldName}" 
                    id="${questionId}"
                    placeholder="<?php echo esc_attr('${placeholder || 'e.g. D02 X285'}'); ?>"
                    maxlength="8"
                    ${required ? 'required' : ''}>
                <a href="https://finder.eircode.ie/" target="_blank" class="wp-form-eircode-finder" style="display: none;">Find your Eircode</a>`;
      break;
    
    case 'numberplate':
      inputHTML = `<input type="text" 
                    class="wp-form-field-input wp-form-numberplate-input" 
                    name="${fieldName}" 
                    id="${questionId}"
                    placeholder="<?php echo esc_attr('${placeholder || 'e.g. 191-D-12345'}'); ?>"
                    maxlength="12"
                    ${required ? 'required' : ''}>`;
      break;
    
    case 'hidden':
      return `<input type="hidden" name="${fieldName}" value="${defaultVal}">`;
    
    default:
      inputHTML = `<input type="text" class="wp-form-field-input" name="${fieldName}" id="${questionId}">`;
  }
  
  return `
                <div class="wp-form-field" style="${style}" data-question-id="${questionId}" ${question.conditionalDisplay ? `data-conditional='${JSON.stringify(question.conditionalDisplay).replace(/'/g, "&#39;")}'` : ''}>
                    <label class="wp-form-field-label" for="${questionId}">
                        <?php echo esc_html('${label}'); ?>
                        ${required ? '<span class="wp-form-field-required">*</span>' : ''}
                    </label>
                    ${inputHTML}
                    ${question.helpText ? `<span class="wp-form-field-help"><?php echo esc_html('${helpText}'); ?></span>` : ''}
                    <span class="wp-form-field-error" style="display: none;"></span>
                </div>`;
}

// Helper: Convert kebab-case to camelCase (must match PHP wp_localize_script variable name)
function toCamelCase(str: string): string {
  return str
    .split('-')
    .map((word, index) => index === 0 ? word : word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}

// Generate Form JavaScript
export function generateFormJS(form: Form): string {
  const { pluginSettings, progressConfig } = form;
  // IMPORTANT: This must match the variable name used in PHP wp_localize_script
  const configVar = toCamelCase(pluginSettings.pluginSlug) + 'Config';
  
  return `/**
 * Form Handler JavaScript
 * Generated by WP Form Builder
 */

(function($) {
    'use strict';
    
    const config = window.${configVar} || {};
    // PHP now returns formConfig as the form object directly (not wrapped in {version, exportedAt, form})
    const formConfig = config.formConfig || {};
    
    // Check if config loaded properly
    const configLoaded = formConfig && formConfig.steps && formConfig.steps.length > 0;
    
    const progressConfig = formConfig.progressConfig || { enabled: true, mode: 'linear', position: 'top' };
    const stepsConfig = formConfig.steps || [];
    const submissionConfig = formConfig.submissionConfig || {};
    
    // Debug logging (enabled for troubleshooting)
    const debug = true;
    function log(...args) {
        if (debug) console.log('[WP-Form]', ...args);
    }
    
    // Log initial config load
    log('=== Form Config Debug ===');
    log('Raw config object:', config);
    log('Config path from PHP:', config.configPath);
    log('formConfig:', formConfig);
    log('Config loaded properly:', configLoaded);
    log('Progress mode:', progressConfig.mode);
    
    // Check for errors from PHP
    if (formConfig.error) {
        console.error('[WP-Form] PHP Error:', formConfig.error, formConfig.message || formConfig.path || '');
    }
    
    // Show visible warning if config failed to load
    if (!configLoaded) {
        console.error('[WP-Form] CRITICAL: Form configuration did not load properly!');
        console.error('[WP-Form] This means validation rules and progress weights will NOT work.');
        console.error('[WP-Form] Please check:');
        console.error('[WP-Form]   1. form-config.json exists in the plugin folder');
        console.error('[WP-Form]   2. The JSON file is valid (no syntax errors)');
        console.error('[WP-Form]   3. PHP has permission to read the file');
    }
    
    log('formConfig.steps:', formConfig.steps);
    log('stepsConfig:', stepsConfig);
    log('stepsConfig is array:', Array.isArray(stepsConfig));
    log('stepsConfig length:', stepsConfig.length);
    if (stepsConfig.length > 0) {
        log('First step:', stepsConfig[0]);
        log('First step id:', stepsConfig[0].id);
        log('First step questions:', stepsConfig[0].questions);
        if (stepsConfig[0].questions && stepsConfig[0].questions.length > 0) {
            log('First question validation:', stepsConfig[0].questions[0].validation);
        }
    } else {
        console.warn('[WP-Form] WARNING: stepsConfig is empty! Validation rules from config will not work.');
        console.warn('[WP-Form] Falling back to HTML5 required attribute validation only.');
    }
    log('=========================');
    
    class FormHandler {
        constructor(formElement) {
            this.form = $(formElement);
            this.container = this.form.closest('.wp-form');
            this.steps = this.form.find('.wp-form-step');
            this.currentStep = 0;
            this.formData = {};
            this.totalSteps = this.steps.length;
            
            log('FormHandler initialized', { totalSteps: this.totalSteps, config: formConfig });
            this.init();
        }
        
        init() {
            this.collectData();
            this.bindEvents();
            this.updateProgress();
            this.evaluateConditionals();
        }
        
        bindEvents() {
            const self = this;
            
            // Navigation buttons
            this.form.on('click', '[data-action="continue"]', function(e) {
                e.preventDefault();
                log('Continue clicked');
                self.nextStep();
            });
            
            this.form.on('click', '[data-action="back"]', function(e) {
                e.preventDefault();
                log('Back clicked');
                self.prevStep();
            });
            
            this.form.on('click', '[data-action="submit"]', function(e) {
                e.preventDefault();
                log('Submit clicked');
                self.submitForm();
            });
            
            // Input changes - collect data and evaluate conditionals
            this.form.on('change input', 'input, textarea, select', function() {
                self.collectData();
                self.evaluateConditionals();
            });
            
            // Rating stars
            this.form.on('click', '.wp-form-rating-star', function() {
                const rating = $(this).closest('.wp-form-rating');
                const value = $(this).data('value');
                rating.find('input[type="hidden"]').val(value).trigger('change');
                rating.find('.wp-form-rating-star').each(function(i) {
                    $(this).toggleClass('active', i < value);
                });
            });
            
            // Slider value display
            this.form.on('input', 'input[type="range"]', function() {
                $(this).siblings('.wp-form-slider-value').text($(this).val());
            });
            
            // Eircode auto-formatting and validation
            this.form.on('input', '.wp-form-eircode-input', function() {
                let value = $(this).val().toUpperCase().replace(/[^A-Z0-9]/g, '');
                // Format as ABC 1234 (Irish eircode format)
                if (value.length > 3) {
                    value = value.substring(0, 3) + ' ' + value.substring(3, 7);
                }
                $(this).val(value.trim());
                
                // Validate eircode prefix and show/hide finder link
                const $field = $(this).closest('.wp-form-field');
                const $finderLink = $(this).siblings('.wp-form-eircode-finder');
                const prefix = value.substring(0, 3).replace(/\\s/g, '');
                
                if (prefix.length >= 3) {
                    if (self.isValidEircodePrefix(prefix)) {
                        $finderLink.hide();
                        $field.removeClass('has-error');
                        $field.find('.wp-form-field-error').hide();
                    } else {
                        $finderLink.show();
                    }
                } else {
                    $finderLink.hide();
                }
            });
            
            // Number plate auto-formatting
            this.form.on('input', '.wp-form-numberplate-input', function() {
                const formatted = self.formatNumberPlate($(this).val());
                $(this).val(formatted);
            });
        }
        
        // Irish eircode prefix validation
        isValidEircodePrefix(prefix) {
            const validPrefixes = [
                'A41','A42','A45','A63','A67','A75','A81','A82','A83','A84','A85','A86','A91','A92','A94','A96','A98',
                'C15',
                'D01','D02','D03','D04','D05','D06','D06W','D07','D08','D09','D10','D11','D12','D13','D14','D15','D16','D17','D18','D20','D22','D24',
                'E21','E25','E32','E34','E41','E45','E53','E91',
                'F12','F23','F26','F28','F31','F35','F42','F45','F52','F56','F91','F92','F93','F94',
                'H12','H14','H16','H18','H23','H53','H54','H62','H65','H71','H91',
                'K32','K34','K36','K45','K56','K67','K78',
                'N37','N39','N41','N91',
                'P12','P14','P17','P24','P25','P31','P32','P36','P43','P47','P51','P56','P61','P67','P72','P75','P81','P85',
                'R14','R21','R32','R35','R42','R45','R51','R56','R93','R95',
                'T12','T23','T34','T45','T56',
                'V14','V15','V23','V31','V35','V42','V92','V93','V94','V95',
                'W12','W23','W34','W91',
                'X35','X42','X91',
                'Y14','Y21','Y25','Y34','Y35'
            ];
            return validPrefixes.includes(prefix.toUpperCase());
        }
        
        // Irish number plate format: YY-C-NNNNNN (e.g., 191-D-12345)
        formatNumberPlate(value) {
            // Remove non-alphanumeric except dashes
            let cleaned = value.toUpperCase().replace(/[^A-Z0-9-]/g, '');
            
            // Remove all existing dashes to reformat
            let noDashes = cleaned.replace(/-/g, '');
            
            if (noDashes.length === 0) return '';
            
            let result = '';
            let year = '';
            let county = '';
            let seq = '';
            
            // Extract year (2-3 digits at start)
            let i = 0;
            while (i < noDashes.length && /\\d/.test(noDashes[i]) && year.length < 3) {
                year += noDashes[i];
                i++;
            }
            
            // Extract county (1-2 letters)
            while (i < noDashes.length && /[A-Z]/.test(noDashes[i]) && county.length < 2) {
                county += noDashes[i];
                i++;
            }
            
            // Extract sequential number (up to 6 digits)
            while (i < noDashes.length && /\\d/.test(noDashes[i]) && seq.length < 6) {
                seq += noDashes[i];
                i++;
            }
            
            // Build result with dashes
            result = year;
            if (county) result += '-' + county;
            if (seq) result += '-' + seq;
            
            return result;
        }
        
        // Validate Irish number plate format
        isValidNumberPlate(value) {
            // Pattern: 2-3 digits, dash, 1-2 letters, dash, 1-6 digits
            return /^\\d{2,3}-[A-Z]{1,2}-\\d{1,6}$/.test(value);
        }
        
        collectData() {
            const self = this;
            // Reset checkbox arrays before collecting
            this.form.find('input[type="checkbox"]').each(function() {
                const name = $(this).attr('name');
                if (name) {
                    self.formData[name.replace('[]', '')] = [];
                }
            });
            
            this.form.find('input, textarea, select').each(function() {
                const $el = $(this);
                const name = $el.attr('name');
                if (!name) return;
                
                const cleanName = name.replace('[]', '');
                
                if ($el.is(':checkbox')) {
                    if ($el.is(':checked')) {
                        if (!Array.isArray(self.formData[cleanName])) {
                            self.formData[cleanName] = [];
                        }
                        self.formData[cleanName].push($el.val());
                    }
                } else if ($el.is(':radio')) {
                    if ($el.is(':checked')) {
                        self.formData[name] = $el.val();
                    }
                } else {
                    self.formData[name] = $el.val();
                }
            });
            
            log('Data collected', this.formData);
        }
        
        validateCurrentStep() {
            const self = this;
            const step = this.steps.eq(this.currentStep);
            const stepId = step.data('step-id');
            
            // Debug: log available config
            log('Steps config available:', stepsConfig);
            log('Looking for stepId:', stepId);
            
            // Ensure stepsConfig is an array
            const stepsArray = Array.isArray(stepsConfig) ? stepsConfig : [];
            const stepConfig = stepsArray.find(s => s.id === stepId) || {};
            
            log('Found step config:', stepConfig);
            log('Questions in step:', stepConfig.questions);
            
            const fields = step.find('.wp-form-field:visible');
            let isValid = true;
            
            log('Validating step', this.currentStep, 'stepId:', stepId, 'fields found:', fields.length);
            
            fields.each(function() {
                const $field = $(this);
                const questionId = $field.data('question-id');
                
                log('Checking field:', questionId);
                
                const questionsArray = Array.isArray(stepConfig.questions) ? stepConfig.questions : [];
                const questionConfig = questionsArray.find(q => q.id === questionId) || {};
                const validation = questionConfig.validation || {};
                
                // Fallback: check if the input has HTML5 required attribute
                const $input = $field.find('input, textarea, select').not('[type="hidden"]').first();
                const hasRequiredAttr = $input.prop('required') || $input.attr('required');
                const isRequired = validation.required || hasRequiredAttr;
                
                log('Question config for', questionId, ':', questionConfig);
                log('Validation rules:', validation, 'HTML required:', hasRequiredAttr, 'Final isRequired:', isRequired);
                
                // Clear previous errors
                $field.removeClass('has-error');
                $field.find('.wp-form-field-error').hide().text('');
                
                // $input is already defined above, no need to redeclare
                if (!$input.length) {
                    // Check for hidden input (rating)
                    const $hidden = $field.find('input[type="hidden"]');
                    if ($hidden.length) {
                        const value = $hidden.val();
                        if (isRequired && (!value || value === '')) {
                            $field.addClass('has-error');
                            $field.find('.wp-form-field-error').text('This field is required').show();
                            isValid = false;
                        }
                    }
                    return;
                }
                
                let value = '';
                
                // Handle different input types
                if ($input.is(':radio') || $input.is(':checkbox')) {
                    const checked = $field.find('input:checked');
                    value = checked.length > 0 ? checked.first().val() : '';
                } else {
                    value = $input.val();
                }
                
                // Required validation
                if (isRequired && (!value || value === '')) {
                    $field.addClass('has-error');
                    $field.find('.wp-form-field-error').text('This field is required').show();
                    isValid = false;
                    log('Validation FAILED: required field empty', questionId, 'isValid now:', isValid);
                    return;
                }
                
                // Skip other validations if empty and not required
                if (!value || value === '') return;
                
                // String length validations
                if (typeof value === 'string') {
                    if (validation.minLength && value.length < validation.minLength) {
                        $field.addClass('has-error');
                        $field.find('.wp-form-field-error').text('Minimum ' + validation.minLength + ' characters required').show();
                        isValid = false;
                        log('Validation failed: minLength', questionId);
                    }
                    
                    if (validation.maxLength && value.length > validation.maxLength) {
                        $field.addClass('has-error');
                        $field.find('.wp-form-field-error').text('Maximum ' + validation.maxLength + ' characters allowed').show();
                        isValid = false;
                        log('Validation failed: maxLength', questionId);
                    }
                    
                    // Pattern validation
                    if (validation.pattern) {
                        try {
                            const regex = new RegExp(validation.pattern);
                            if (!regex.test(value)) {
                                $field.addClass('has-error');
                                $field.find('.wp-form-field-error').text(validation.patternMessage || 'Invalid format').show();
                                isValid = false;
                                log('Validation failed: pattern', questionId);
                            }
                        } catch (e) {
                            log('Invalid regex pattern', validation.pattern);
                        }
                    }
                }
                
                // Number validations
                if ($input.attr('type') === 'number') {
                    const numValue = parseFloat(value);
                    if (validation.min !== undefined && numValue < validation.min) {
                        $field.addClass('has-error');
                        $field.find('.wp-form-field-error').text('Minimum value is ' + validation.min).show();
                        isValid = false;
                    }
                    if (validation.max !== undefined && numValue > validation.max) {
                        $field.addClass('has-error');
                        $field.find('.wp-form-field-error').text('Maximum value is ' + validation.max).show();
                        isValid = false;
                    }
                }
                
                // Email validation
                if ($input.attr('type') === 'email' && value) {
                    const emailRegex = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;
                    if (!emailRegex.test(value)) {
                        $field.addClass('has-error');
                        $field.find('.wp-form-field-error').text('Please enter a valid email address').show();
                        isValid = false;
                    }
                }
                
                // Eircode validation
                if ($input.hasClass('wp-form-eircode-input') && value) {
                    const prefix = value.substring(0, 3).replace(/\\s/g, '');
                    if (!self.isValidEircodePrefix(prefix)) {
                        $field.addClass('has-error');
                        $field.find('.wp-form-field-error').text('Please enter a valid Irish eircode').show();
                        isValid = false;
                    }
                }
                
                // Number plate validation
                if ($input.hasClass('wp-form-numberplate-input') && value) {
                    if (!self.isValidNumberPlate(value)) {
                        $field.addClass('has-error');
                        $field.find('.wp-form-field-error').text('Please enter a valid Irish number plate (e.g., 191-D-12345)').show();
                        isValid = false;
                    }
                }
            });
            
            log('After validation loop, isValid =', isValid);
            
            // Scroll to first error
            if (!isValid) {
                log('Validation FAILED - blocking navigation');
                const firstError = step.find('.has-error').first();
                if (firstError.length) {
                    $('html, body').animate({
                        scrollTop: firstError.offset().top - 100
                    }, 300);
                }
            }
            
            log('Validation result returning:', isValid);
            return isValid;
        }
        
        evaluateCondition(condition) {
            if (!condition || !condition.rules || condition.rules.length === 0) {
                return true;
            }
            
            const rules = condition.rules;
            const logic = condition.logic || 'AND';
            
            const results = rules.map(rule => this.evaluateRule(rule));
            
            return logic === 'AND' 
                ? results.every(r => r) 
                : results.some(r => r);
        }
        
        evaluateRule(rule) {
            if (!rule || !rule.questionId) return true;
            
            const value = this.formData[rule.questionId] || '';
            const compareValue = rule.value || '';
            
            switch (rule.operator) {
                case 'equals': return String(value) === String(compareValue);
                case 'not_equals': return String(value) !== String(compareValue);
                case 'contains': return String(value).toLowerCase().includes(String(compareValue).toLowerCase());
                case 'not_contains': return !String(value).toLowerCase().includes(String(compareValue).toLowerCase());
                case 'is_empty': return !value || value === '' || (Array.isArray(value) && value.length === 0);
                case 'is_not_empty': return value && value !== '' && (!Array.isArray(value) || value.length > 0);
                case 'greater_than': return Number(value) > Number(compareValue);
                case 'less_than': return Number(value) < Number(compareValue);
                default: return true;
            }
        }
        
        evaluateConditionals() {
            const self = this;
            
            this.form.find('[data-conditional]').each(function() {
                try {
                    const conditionData = $(this).data('conditional');
                    const condition = typeof conditionData === 'string' ? JSON.parse(conditionData) : conditionData;
                    const shouldShow = self.evaluateCondition(condition);
                    $(this).toggle(shouldShow);
                } catch (e) {
                    log('Error evaluating conditional', e);
                }
            });
        }
        
        getNextStepIndex() {
            const step = this.steps.eq(this.currentStep);
            const stepId = step.data('step-id');
            const stepConfig = stepsConfig.find(s => s.id === stepId);
            
            if (!stepConfig) return this.currentStep + 1;
            
            // Check conditional navigation
            const conditionalNav = stepConfig.conditionalNavigation || [];
            const sortedNav = [...conditionalNav].sort((a, b) => (b.priority || 0) - (a.priority || 0));
            
            for (const nav of sortedNav) {
                if (this.evaluateCondition(nav.condition)) {
                    if (nav.target.type === 'submit') return -1;
                    if (nav.target.type === 'specific' && nav.target.stepId) {
                        const targetIndex = stepsConfig.findIndex(s => s.id === nav.target.stepId);
                        if (targetIndex !== -1) return targetIndex;
                    }
                    if (nav.target.type === 'next') return this.currentStep + 1;
                }
            }
            
            return this.currentStep + 1;
        }
        
        nextStep() {
            if (!this.validateCurrentStep()) {
                log('Validation failed, staying on current step');
                return;
            }
            
            this.collectData();
            const nextIndex = this.getNextStepIndex();
            log('Next step index', nextIndex);
            
            if (nextIndex === -1 || nextIndex >= this.totalSteps) {
                this.submitForm();
            } else {
                this.goToStep(nextIndex);
            }
        }
        
        prevStep() {
            if (this.currentStep > 0) {
                this.goToStep(this.currentStep - 1);
            }
        }
        
        goToStep(index) {
            const self = this;
            log('Going to step', index);
            
            this.steps.eq(this.currentStep).fadeOut(200, function() {
                self.currentStep = index;
                self.steps.eq(self.currentStep).fadeIn(200);
                self.updateProgress();
                self.evaluateConditionals();
                
                // Scroll to top of form
                $('html, body').animate({
                    scrollTop: self.container.offset().top - 50
                }, 300);
            });
        }
        
        updateProgress() {
            if (!progressConfig.enabled) {
                log('Progress bar disabled');
                return;
            }
            
            const currentStepNumber = this.currentStep + 1;
            let progress = 0;
            
            switch (progressConfig.mode) {
                case 'linear':
                case 'step_based':
                    progress = (currentStepNumber / this.totalSteps) * 100;
                    break;
                case 'weighted':
                    const weights = progressConfig.stepWeights || {};
                    let totalWeight = 0;
                    let completedWeight = 0;
                    stepsConfig.forEach((s, i) => {
                        const w = weights[s.id] || 1;
                        totalWeight += w;
                        if (i < currentStepNumber) completedWeight += w;
                    });
                    progress = totalWeight > 0 ? (completedWeight / totalWeight) * 100 : 0;
                    break;
                case 'exponential':
                default:
                    // Exponential progress curve - feels faster at the start
                    const growthRate = 5;
                    const normalised = currentStepNumber / this.totalSteps;
                    const expFactor = 1 - Math.exp(-growthRate);
                    if (expFactor !== 0) {
                        progress = ((1 - Math.exp(-growthRate * normalised)) / expFactor) * 100;
                    } else {
                        progress = normalised * 100;
                    }
                    break;
            }
            
            // Ensure progress is between 0 and 100
            progress = Math.max(0, Math.min(100, Math.round(progress)));
            
            log('Progress updated', { step: currentStepNumber, total: this.totalSteps, progress });
            
            // Update all progress elements
            this.container.find('.wp-form-progress-fill').css('width', progress + '%');
            this.container.find('.wp-form-progress-percentage').text(progress + '%');
            this.container.find('.current-step').text(currentStepNumber);
            this.container.find('.total-steps').text(this.totalSteps);
        }
        
        showLoading() {
            this.container.addClass('wp-form-loading');
            this.form.find('button').prop('disabled', true);
        }
        
        hideLoading() {
            this.container.removeClass('wp-form-loading');
            this.form.find('button').prop('disabled', false);
        }
        
        submitForm() {
            if (!this.validateCurrentStep()) {
                log('Submit validation failed');
                return;
            }
            
            this.collectData();
            this.showLoading();
            
            log('Submitting form', this.formData);
            log('Submission config', submissionConfig);
            
            // Use custom URL if configured, otherwise use WordPress AJAX
            const useCustomUrl = submissionConfig.url && submissionConfig.url.trim() !== '';
            const submitUrl = useCustomUrl ? submissionConfig.url : config.ajaxUrl;
            const submitData = useCustomUrl 
                ? this.formData 
                : {
                    action: '${pluginSettings.pluginSlug.replace(/-/g, '_')}_submit',
                    nonce: config.nonce,
                    formData: JSON.stringify(this.formData)
                };
            
            log('Submitting to', submitUrl, 'with data', submitData);
            
            $.ajax({
                url: submitUrl,
                type: submissionConfig.method || 'POST',
                data: useCustomUrl ? JSON.stringify(submitData) : submitData,
                contentType: useCustomUrl ? 'application/json' : 'application/x-www-form-urlencoded; charset=UTF-8',
                success: (response) => {
                    this.hideLoading();
                    log('Submit response', response);
                    
                    // For custom URLs, any response is considered success
                    const isSuccess = useCustomUrl ? true : (response && response.success);
                    
                    if (isSuccess) {
                        // Complete the progress bar on success
                        this.container.find('.wp-form-progress-fill').css('width', '100%');
                        this.container.find('.wp-form-progress-percentage').text('100%');
                        
                        // Show success message
                        this.form.fadeOut(200, () => {
                            this.container.find('.wp-form-success').fadeIn(200);
                        });
                        
                        // Handle redirect if specified (check submissionConfig first, then response)
                        const redirectUrl = submissionConfig.redirectOnSuccess || 
                            (response && response.data && response.data.redirect);
                        if (redirectUrl) {
                            log('Redirecting to', redirectUrl);
                            setTimeout(() => {
                                window.location.href = redirectUrl;
                            }, 2000);
                        }
                    } else {
                        const errorMsg = (response && response.data && response.data.message) 
                            ? response.data.message 
                            : 'Submission failed. Please try again.';
                        this.showError(errorMsg);
                    }
                },
                error: (xhr, status, error) => {
                    this.hideLoading();
                    log('Submit error', status, error, xhr.responseText);
                    this.showError('An error occurred while submitting the form. Please check your connection and try again.');
                }
            });
        }
        
        showError(message) {
            // Create or update error message element
            let $error = this.container.find('.wp-form-submission-error');
            if (!$error.length) {
                $error = $('<div class="wp-form-submission-error"></div>');
                this.form.prepend($error);
            }
            $error.text(message).show();
            
            // Scroll to error
            $('html, body').animate({
                scrollTop: $error.offset().top - 50
            }, 300);
            
            // Auto-hide after 5 seconds
            setTimeout(() => {
                $error.fadeOut(300);
            }, 5000);
        }
    }
    
    // Initialize when DOM is ready - with guard against double initialization
    $(document).ready(function() {
        log('Initializing form handlers');
        $('.wp-form .wp-form-container').each(function() {
            const $form = $(this);
            // Check if already initialized
            if ($form.data('wp-form-initialized')) {
                log('Form already initialized, skipping');
                return;
            }
            $form.data('wp-form-initialized', true);
            new FormHandler(this);
        });
    });
    
})(jQuery);
`;
}
